### ISSUE TITLE
Label spaces cause break

### ISSUE THREAD

**Issue by tjperry07** [cncws/markdown-it-codetabs#1]
The plugin works amazing. One issue is when you add a space in a label name, it breaks in the output. It renders only one tab. 

It might make sense to [capture and render anything](https://github.com/cncws/markdown-it-codetabs/blob/main/index.js#L9) after `:`. 

`\[(\w*)(?::(\w.*))?\]` Added a `.` period. 

# MD file

~~~
```js [g1:Hello Hi]
console.log("hello");
```

```py [g1:Python3]
print("hello")
```



```py [g2:Python2]
print("hello")
```
```js [g2:JavaScript]
console.log("hello");
```

```js
console.log("Hello");
```
~~~

# Output

In the first two code blocks, you can see Python is working, but it renders Hello Hi as a standard code block, even though it's grouped. 

<img width="722" alt="Screen Shot 2021-01-04 at 2 33 33 PM" src="https://user-images.githubusercontent.com/5667652/103577156-e1314f00-4e99-11eb-8939-250490e18d66.png">

**Comment by cncws** [comment]
Thank you for comment.
It's definitely not proper that label names can't use space. But I don't want capture anything, it makes label name complex.
Instead, I updated the RE by `/\[(\w*)(?::([\w ]*))?\]/` to capture ` ` or `\w`. Hope this little update can help you.
